### ISSUE TITLE
Node is not splitable exception

### ISSUE THREAD

**Issue by gfonsecabr** [CG-SHOP/pyutils24#1]
On some possibly bad solution files, calling verify throws an exception that it is not supposed to and gives no information to what the problem in the file is:

Traceback (most recent call last):
  File "/home/fonseca/Documents/src/socg24challenge/./testsol.py", line 19, in <module>
    value = verify(instance, solution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fonseca/.local/lib/python3.11/site-packages/cgshop2024_pyutils/verify.py", line 42, in verify
    knapsack.add_item(poly)  # will throw an exception if the item does not fit
    ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Node is not splitable.

**Comment by d-krupke** [comment]
Oh. That is a problem in my QuadTree. It has reached a level where it can no longer split without becoming fractional. Can you by any chance mail me the file?
~~Otherwise, one can do a quick workaround by enforcing the fill limit only if the node is splitable.~~ (Don't do that. It can result in excessive memory consumption) I added this as I did not expect this to happen, but I can now imagine cases were this is necessary.

**Comment by gfonsecabr** [comment]
Done

**Comment by d-krupke** [comment]
I may have a fix. Version 1.0.2 now runs through the test cases and tells me that your solution is fine. Will have to double check the correctness as the quadtree is now working differently and if I messed up it could forget some elements. Too tired for that right now.

**Comment by d-krupke** [comment]
There is a new version on PyPI. We will double-check the correctness the next days.

**Comment by gfonsecabr** [comment]
Thanks, I updated with pip and the error is gone.
